<?php
// $Id$
/**
 * @file report.module
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_perm().
 */
function report_perm() {
  return array('generate report');
}

/**
 * Implementation of hook_menu().
 */
function report_menu() { 
  	$items['report/excel'] = array(
    	'title' => 'รายงานประจำเดือน',
    	'page callback' => 'report_new',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
  	);

	$items['report/excel/new'] = array(
    	'title' => 'รายงานการออกตั๋วจำนำประจำเดือน',
    	'page callback' => 'report_new_ticket',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_new_ticket.inc'
  	);

	$items['report/view/new'] = array(
    	'title' => 'รายงานการออกตั๋วจำนำประจำเดือน',
    	'page callback' => 'report_new_ticket_view',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_new_ticket.inc'
  	);

	$items['report/excel/cancel'] = array(
    	'title' => 'รายงานตั๋วจำนำที่ถูกยกเลิกประจำเดือน',
    	'page callback' => 'report_cancel',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_cancel.inc'
  	);

	
	$items['report/view/cancel'] = array(
    	'title' => 'รายงานตั๋วจำนำที่ถูกยกเลิกประจำเดือน',
    	'page callback' => 'report_cancel_view',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_cancel.inc'
  	);

	$items['report/excel/out-time'] = array(
    	'title' => 'รายงานตั๋วที่ขาดจำนำประจำเดือน',
    	'page callback' => 'report_out_time',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_out_time.inc'
  	);

	$items['report/view/out-time'] = array(
    	'title' => 'รายงานตั๋วที่ขาดจำนำประจำเดือน',
    	'page callback' => 'report_out_time_view',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_out_time.inc'
  	);

	$items['report/excel/closed'] = array(
    	'title' => 'รายงานการไถ่ถอนตั๋วจำนำประจำเดือน',
    	'page callback' => 'report_closed',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_closed.inc'
  	);

	$items['report/view/closed'] = array(
    	'title' => 'รายงานการไถ่ถอนตั๋วจำนำประจำเดือน',
    	'page callback' => 'report_closed_view',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_closed.inc'
  	);

	$items['report/excel/withdraw'] = array(
    	'title' => 'รายงานการไถ่ถอนบางส่วนประจำเดือน',
    	'page callback' => 'report_withdraw',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_withdraw.inc'
  	);

	$items['report/view/withdraw'] = array(
    	'title' => 'รายงานการไถ่ถอนบางส่วนประจำเดือน',
    	'page callback' => 'report_withdraw_view',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'report_withdraw.inc'
  	);

	$items['report/excel/reduce'] = array(
    	'title' => 'รายงานตั๋วจำนำขอลดยอดเงินต้นประจำเดือน',
    	'page callback' => 'report_reduce',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'reduce_withdraw.inc'
  	);

	$items['report/view/reduce'] = array(
    	'title' => 'รายงานตั๋วจำนำขอลดยอดเงินต้นประจำเดือน',
    	'page callback' => 'report_reduce_view',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'reduce_withdraw.inc'
  	);

	$items['report/excel/add-cost'] = array(
    	'title' => 'รายงานตั๋วจำนำขอเพ่ิมยอดเงินต้นประจำเดือน',
    	'page callback' => 'report_add_cost',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'add_cost_withdraw.inc'
  	);

	$items['report/view/add-cost'] = array(
    	'title' => 'รายงานตั๋วจำนำขอเพ่ิมยอดเงินต้นประจำเดือน',
    	'page callback' => 'report_add_cost_view',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'add_cost_withdraw.inc'
  	);
	
	$items['report/excel/conclusion'] = array(
    	'title' => 'รายงานสรุปยอดเงินประจำเดือน',
    	'page callback' => 'report_conclusion',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'conclustion.inc'
  	);

	$items['report/view/conclusion'] = array(
    	'title' => 'รายงานสรุปยอดเงินประจำเดือน',
    	'page callback' => 'report_conclusion_view',
    	'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'conclustion.inc'
  	);

	$items['report/view/lost-ticket'] = array(
		'title' => 'รายงานสรุปยอดตั๋วหายประจำเดือน',
		'page callback' => 'report_lost_ticket',
		'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'lost_ticket.inc'
	);

	$items['report/excel/lost-ticket'] = array(
		'title' => 'รายงานสรุปยอดตั๋วหายประจำเดือน',
		'page callback' => 'report_lost_ticket_excel',
		'access arguments' => array('generate report'),
		'type' => MENU_CALLBACK,
		'file' => 'lost_ticket.inc'
	);
	
  	return $items;
}

/**
 * function
 */
function report_set_breadcrumb(){
	$breadcrumb = array();
	$breadcrumb[] = l('Home', NULL);
	$breadcrumb[] = l('รายงานประจำเดือน', 'report/excel');
	
	drupal_set_breadcrumb($breadcrumb);
}

/**
 * function
 */
function report_new(){
	global $user;
	
	$output = '';
	$output .= drupal_get_form(report_date_filter_form);
	
	if ($user->report_date != "") {
		$rows = array();
		
		$link1 = 'ออกรายงาน';
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานการออกตั๋วจำนำ'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/new")),
		);
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานการยกเลิกตั๋วจำนำ'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/cancel")),
		);
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานตั๋วขาดจำนำ'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/out-time")),
		);
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานการไถ่ถอนตั๋วจำนำ'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/closed")),
		);
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานการไถ่ถอนบางส่วน'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/withdraw")),
		);
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานตั๋วจำนำขอลดยอดเงินต้น'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/reduce")),
		);
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานตั๋วจำนำขอเพิ่มยอดเงินต้น'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/add-cost")),
		);
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานสรุปยอดเงิน'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/conclusion")),
		);
		
		$rows[] = array(
			array('class'=>'title', 'data'=>'รายงานสรุปยอดตั๋วหาย'),
			array('class'=>'link', 'data'=>l("แสดงรายงาน", "report/view/lost-ticket")),
		);
	}
	
	$header = array(
		array('class'=>'title', 'data'=>'ชื่อรายงาน'),
		array('class'=>'title', 'data'=>'แสดงรายงาน'),
	);
	
	$output .= '<div class="report-table">'.theme('table', $header, $rows).'</div>';
	
	return $output;
}

/**
 * function
 */
function report_date_filter_form($form_state){
	global $user;
	
	if ($user->report_date != "") {
		list($day, $month, $year) = explode('-', $user->report_date);
		list($day2, $month2, $year2) = explode('-', $user->report_date2);
	}
	else {
		$day = date('d');
		$month = date('m');
		$year = date('Y');
		
		$day2 = date('d');
		$month2 = date('m');
		$year2 = date('Y');
	}
	
	$day_options = array();
	for ($i=1; $i <= 31; $i++) { 
		$day_options[$i] = $i;
	}
	
	$form = array();
	$form['day'] = array(
		'#type' => 'select',
		'#title' => 'วันที่',
		'#options' => $day_options,
		'#default_value' => array($day),
	);
	
	$form['month'] = array(
		'#type' => 'select',
		'#title' => 'เดือน',
		'#options' => report_get_month(),
		'#default_value' => array($month),
	);
	
	$form['year'] = array(
		'#type' => 'select',
		'#title' => 'ปี',
		'#options' => report_get_year(),
		'#default_value' => array($year),
	);
	
	$form['day2'] = array(
		'#type' => 'select',
		'#title' => 'วันที่',
		'#options' => $day_options,
		'#default_value' => array($day2),
	);
	
	$form['month2'] = array(
		'#type' => 'select',
		'#title' => 'เดือน',
		'#options' => report_get_month(),
		'#default_value' => array($month2),
	);
	
	$form['year2'] = array(
		'#type' => 'select',
		'#title' => 'ปี',
		'#options' => report_get_year(),
		'#default_value' => array($year2),
	);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'ออกรายงาน'
	);
	
	return $form;
}

function report_date_filter_form_submit($form_id, $form_state){
	global $user;
	
	$date = $form_state['values']['day']."-".$form_state['values']['month']."-".$form_state['values']['year'];
	$report_date = array('report_date' => $date); 
	user_save($user, $report_date);
	
	$date2 = $form_state['values']['day2']."-".$form_state['values']['month2']."-".$form_state['values']['year2'];
	$report_date2 = array('report_date2' => $date2); 
	user_save($user, $report_date2);
}

function theme_report_date_filter_form($form) {
	$output = '<div class="report-date-filter">
					<div class="grid_4">'.drupal_render($form['day']).'</div>
					<div class="grid_1">'.drupal_render($form['month']).'</div>
					<div class="grid_2">'.drupal_render($form['year']).'</div>
					
					<div class="grid_5">'.t('ถึง').'</div>
					
					<div class="grid_4">'.drupal_render($form['day2']).'</div>
					<div class="grid_1">'.drupal_render($form['month2']).'</div>
					<div class="grid_2">'.drupal_render($form['year2']).'</div>
					
					<div class="grid_3">'.drupal_render($form['submit']).'</div>
					<div class="clear-block"></div>
			   </div>';
			
	$output .= drupal_render($form);
			
 	return $output;
}

/**
 * function
 */
function report_get_detail_all(&$transaction_nid){
	$result = db_query("SELECT n.title as gold_type_name,
		 					   d.field_transaction_sub_detail_value as detail,
		 					   d.field_transaction_weight_value as weight,
		 					   d.field_transaction_unit_value as unit 
						FROM {content_type_transaction_detail} d 
						INNER JOIN {node} n ON n.nid=d.field_gold_type_ref_nid 
						WHERE d.field_transaction_ref_nid=%d", $transaction_nid);
					
	while ($detail = db_fetch_object($result)) {
		$list[] = $detail->gold_type_name." ".$detail->detail." ".$detail->weight." ".$detail->unit;
	}
	
	return $list;
}

/**
 * function
 */
function report_get_year(){
	$current = date("Y");
	$list = array();
	
	for ($i=0; $i < 10; $i++) { 
		$year = $current - $i;
		$list[$year] = $year + 543;
	}
	
	return $list;
}

function report_get_month() {
	$list = array(
			1 => "มกราคม",	
			2 => "กุมภาพันธ์",
			3 => "มีนาคม",	
			4 => "เมษายน",	
			5 => "พฤษภาคม",	
			6 => "มิถุนายน",	
			7 => "กรกฎาคม",	
			8 => "สิงหาคม",	
			9 => "กันยายน",	
			10 => "ตุลาคม",	
			11 => "พฤศจิกายน",
			12 => "ธันวาคม"
		);
		
	return $list;
}

/**
 * Convert String
 **/
function report_conv($str) {
	return iconv('UTF-8', 'TIS-620', $str);
}



/**
 * Implementation of hook_theme().
 */
function report_theme($existing, $type, $theme, $path) {
  return array(
    'report_date_filter_form' => array(
      'arguments' => array('arg1' => NULL, 'arg2' => 0, 'arg3' => FALSE),
    ),
  );
}

/**
 * Convert String
 **/
function excel_report_conv($str) {
	return iconv('UTF-8', 'TIS-620', $str);
}


